"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import warnings

# Cosmetic warnings from third-party packages that show up on every manage.py
# command (not just ask) because importing cloudinary/google-auth here (and
# via every INSTALLED_APPS module Django loads) triggers them before any
# command runs. Must come before those imports below, not after.
warnings.filterwarnings('ignore', message=r'urllib3 v2 only supports OpenSSL.*')
warnings.filterwarnings('ignore', category=FutureWarning, module=r'google(\.|$)')

import os
from datetime import timedelta
from pathlib import Path
import cloudinary
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

AUTH_USER_MODEL = 'core.User'

FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:5173')

GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', default='')

ANTHROPIC_API_KEY = env('ANTHROPIC_API_KEY', default='')

# Sends via Brevo's transactional email API (core/email_backend.py) once
# BREVO_API_KEY is set — no SMTP host/port/credentials needed. Unset (local
# dev without a Brevo account) falls back to Django's console backend, same
# as before. See the ENVIRONMENT==production guard below for why this can't
# silently stay on the console backend in production.
BREVO_API_KEY = env('BREVO_API_KEY', default='')
EMAIL_BACKEND = 'core.email_backend.BrevoAPIBackend' if BREVO_API_KEY else 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@example.com')



cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True,
)


load_dotenv()

GROQ_API_KEY = os.getenv(
    "GROQ_API_KEY"
)






# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'core',
    'games',
    'organizer',
    'tourny_regist',
    'brackets',
    'partners',
    'dashboard',
    'rag_chat',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        # ScopedRateThrottle only applies to views that opt in with throttle_scope
        # (login/register/email_action/chat/team_join below); User/AnonRateThrottle
        # apply globally so no endpoint is left completely unthrottled. Rates are
        # deliberately generous — this is a baseline ceiling against scripted abuse,
        # not meant to constrain normal interactive use.
        'rest_framework.throttling.ScopedRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ),
    'EXCEPTION_HANDLER': 'core.exceptions.security_aware_exception_handler',
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
        'register': '20/hour',
        'email_action': '5/hour',
        'chat': '20/min',
        'team_join': '20/min',
        'user': '1000/min',
        'anon': '200/min',
        # Keyed by the submitted email/account identifier rather than client
        # IP (see core/throttling.py) — layered on top of the IP-scoped rates
        # above so a login/reset attack distributed across many IPs still
        # hits a per-account ceiling.
        'login_email': '10/min',
        'email_action_email': '5/hour',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = env.list('CORS_ORIGINS', default=['http://localhost:5173'])
# The frontend authenticates with a bearer token in the Authorization header,
# never a cookie — no view relies on a cross-site cookie, so there is nothing
# for CORS_ALLOW_CREDENTIALS=True to legitimately unlock. Keeping it False
# means a browser will never attach cookies to a cross-origin request to this
# API even if one were accidentally set later.
CORS_ALLOW_CREDENTIALS = False

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=['http://localhost:5173'])

# Production hardening (safe no-ops in local dev where DEBUG=True)
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=not DEBUG)
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0 if DEBUG else 31536000)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

ENVIRONMENT = env('ENVIRONMENT', default='development')

# Without BREVO_API_KEY, EMAIL_BACKEND above silently fell back to the
# console backend, which prints full email bodies — including password-reset
# and email-verification links with their signed tokens — to stdout. Fine in
# dev; a real credential/token leak (into deploy logs, log aggregators,
# anyone with log access) if it were ever left that way in production. Same
# "refuse to start" treatment as SECRET_KEY/JWT_SECRET_KEY, for the same
# reason: better to fail loudly at startup than silently leak tokens to logs.
if ENVIRONMENT == 'production' and not BREVO_API_KEY:
    raise ImproperlyConfigured(
        'BREVO_API_KEY is not set in production — email would silently fall back to the console '
        'backend, printing password-reset/verification links (with their tokens) to stdout '
        'instead of emailing them. Set BREVO_API_KEY in the production environment.'
    )

DATABASE_URL = (
    env('DATABASE_URL_PROD') if ENVIRONMENT == 'production' else env('DATABASE_URL_DEV')
)

DATABASES = {
    'default': env.db_url_config(DATABASE_URL),
}
_db_options = DATABASES['default'].setdefault('OPTIONS', {})
_db_options.pop('pgbouncer', None)
# Encryption in transit was previously entirely up to whoever set
# DATABASE_URL_PROD (e.g. an `sslmode=require` query param) — a deployment
# with that param simply omitted would connect over plaintext with no error.
# Enforce it here for production instead of only documenting it; a
# `sslmode`/`ssl` already present in the URL (parsed into _db_options above)
# is left untouched, so this only fills the gap, it doesn't fight the URL.
if ENVIRONMENT == 'production':
    _db_options.setdefault('sslmode', 'require')


# Cache — used for DRF throttling (ScopedRateThrottle/UserRateThrottle/
# AnonRateThrottle all read/write counters here). Without REDIS_URL this
# falls back to Django's default LocMemCache, which is *per-process*: behind
# a multi-worker/multi-instance deployment (gunicorn -w N, multiple Render
# instances, ...) each process keeps its own counter, so the effective rate
# limit is (configured rate) x (worker count), not the configured rate. Set
# REDIS_URL in production to give every process a shared, correct counter.
REDIS_URL = env('REDIS_URL', default='')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        },
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'core.validators.MaximumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'core.validators.StrongPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True






AUTH_PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    'AUTH_HEADER_TYPES': ('Bearer',),

    'SIGNING_KEY': env('JWT_SECRET_KEY'),
    # Pinned explicitly rather than relying on SimpleJWT's own default: a
    # symmetric algorithm here must always mean SIGNING_KEY, never a
    # public/private keypair, and locking this down means a future settings
    # change can't silently widen what algorithm a token is accepted under.
    'ALGORITHM': 'HS256',
}
# Optional error/security-event monitoring. Unset in dev and CI (no DSN —
# nothing is sent anywhere); set SENTRY_DSN in production to get alerted on
# unhandled 5xx errors and the security-relevant 401/403/429s
# core.exceptions.security_aware_exception_handler logs (Sentry's logging
# integration below captures ERROR-level log records as events, and the
# 'security' logger stays INFO-level by design — see LOGGING below — so
# route actual alerting off the log aggregator's own rules on that logger,
# not off Sentry event volume, unless you deliberately want every one of
# those to also page).
SENTRY_DSN = env('SENTRY_DSN', default='')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        environment=ENVIRONMENT,
        # Errors only — no performance/trace sampling, and no automatic PII
        # (request bodies, cookies, user email) attached to events beyond
        # what's explicitly captured elsewhere in this codebase.
        traces_sample_rate=0.0,
        send_default_pii=False,
    )

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        # Django's own default config only sends django.request (unhandled
        # 500s, full traceback via exc_info) to console when DEBUG=True —
        # gated by its 'require_debug_true' filter. With DEBUG correctly off
        # in production, that left server errors completely unlogged
        # anywhere. This entry restores console output for them regardless
        # of DEBUG, unfiltered.
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'rag_chat': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # core.security_events.log_security_event's target — kept as its own
        # logger (rather than reusing 'core') so a log aggregator/Sentry
        # alert rule can filter on it specifically without picking up every
        # other core.* log line too.
        'security': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
