# Generated by Django 4.2.30 on 2026-07-22 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tourny_regist.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourny_regist', '0002_tournament_created_by_tournament_is_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('invite_code', models.CharField(default=tourny_regist.models._generate_invite_code, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='is_public',
        ),
        migrations.AddField(
            model_name='tournament',
            name='bracket_format',
            field=models.CharField(choices=[('single', 'Single Elimination'), ('double', 'Double Elimination'), ('guarantee3', '3-Game Guarantee'), ('round_robin', 'Round Robin'), ('swiss', 'Swiss System'), ('group_playoff', 'Group Stage + Playoff')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='tournaments/business_license/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='company_registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='tournaments/company_registration_certificate/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='contact_company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tournament',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tournament',
            name='contact_emergency_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tournament',
            name='contact_organizer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tournament',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tournament',
            name='contact_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='discord_server',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizer_cnic_back',
            field=models.FileField(blank=True, null=True, upload_to='tournaments/organizer_cnic_back/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizer_cnic_front',
            field=models.FileField(blank=True, null=True, upload_to='tournaments/organizer_cnic_front/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_pool',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='room_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='social_discord',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='social_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='social_instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='social_youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sponsor_agreement',
            field=models.FileField(blank=True, null=True, upload_to='tournaments/sponsor_agreement/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tax_certificate',
            field=models.FileField(blank=True, null=True, upload_to='tournaments/tax_certificate/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_map_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_parking_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tourny_regist.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tourny_regist.tournament'),
        ),
        migrations.AddField(
            model_name='registration',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='tourny_regist.team'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'player'), name='unique_team_membership'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_team_name_per_tournament'),
        ),
    ]
