# Generated by Django 4.2.30 on 2026-07-22 19:48

from django.db import migrations, models


def publish_already_approved_tournaments(apps, schema_editor):
    # Publishing is a new, separate step from admin approval — without this, every
    # tournament an admin already approved before this change shipped would silently
    # vanish from the public list until its organizer went and published it.
    # Grandfather them in instead.
    Tournament = apps.get_model('tourny_regist', 'Tournament')
    Tournament.objects.filter(status='approved').update(is_published=True)


class Migration(migrations.Migration):

    dependencies = [
        ('tourny_regist', '0004_registration_accepted_code_of_conduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(publish_already_approved_tournaments, migrations.RunPython.noop),
    ]
