# Generated by Django 4.2.30 on 2026-07-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourny_regist', '0006_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/covers/%Y/%m/'),
        ),
    ]
