# Generated by Django 4.2.30 on 2026-08-02 13:39

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourny_regist', '0007_tournament_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, storage=core.storage.CloudinarySignedStorage(), upload_to='registrations/payment_proof/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='business_license',
            field=models.FileField(blank=True, null=True, storage=core.storage.CloudinarySignedStorage(), upload_to='tournaments/business_license/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='company_registration_certificate',
            field=models.FileField(blank=True, null=True, storage=core.storage.CloudinarySignedStorage(), upload_to='tournaments/company_registration_certificate/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='organizer_cnic_back',
            field=models.FileField(blank=True, null=True, storage=core.storage.CloudinarySignedStorage(), upload_to='tournaments/organizer_cnic_back/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='organizer_cnic_front',
            field=models.FileField(blank=True, null=True, storage=core.storage.CloudinarySignedStorage(), upload_to='tournaments/organizer_cnic_front/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='sponsor_agreement',
            field=models.FileField(blank=True, null=True, storage=core.storage.CloudinarySignedStorage(), upload_to='tournaments/sponsor_agreement/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tax_certificate',
            field=models.FileField(blank=True, null=True, storage=core.storage.CloudinarySignedStorage(), upload_to='tournaments/tax_certificate/%Y/%m/'),
        ),
    ]
