# Generated by Django 4.2.30 on 2026-08-02 17:30

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourny_regist', '0009_alter_registration_payment_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, validators=[core.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, validators=[core.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='contact_emergency_phone',
            field=models.CharField(blank=True, max_length=30, validators=[core.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, validators=[core.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_pool',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='team_size',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
