# Generated by Django 4.2.30 on 2026-08-19 11:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourny_regist', '0011_tournament_champion_tournament_champion_declared_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='check_in_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='check_in_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='game_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_participants',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='server_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='tournament_ends_at_after_starts_at'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(check=models.Q(('min_participants__isnull', True), ('max_participants__isnull', True), ('min_participants__lte', models.F('max_participants')), _connector='OR'), name='tournament_min_lte_max_participants'),
        ),
    ]
