# Generated by Django 4.2.30 on 2026-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourny_regist', '0014_roster_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='seed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
