# Generated by Django 4.2.30 on 2026-08-19 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourny_regist', '0015_bracket_seeding_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accepted_rules_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TournamentRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('match_format_rules', models.TextField(blank=True)),
                ('conduct_rules', models.TextField(blank=True)),
                ('scoring_rules', models.TextField(blank=True)),
                ('penalties_and_disqualification', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_versions', to='tourny_regist.tournament')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='tournamentruleversion',
            constraint=models.UniqueConstraint(fields=('tournament', 'version'), name='unique_tournament_rule_version'),
        ),
    ]
