# Generated by Django 4.2.30 on 2026-08-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_alter_organizer_user'),
        ('tourny_regist', '0016_registration_accepted_rules_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='organizer.organizer'),
        ),
    ]
