# Generated by Django 4.2.30 on 2026-07-20 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['bracket_side', 'round_number', 'position']},
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='unique_match_slot',
        ),
        migrations.AddField(
            model_name='bracket',
            name='format',
            field=models.CharField(choices=[('single', 'Single Elimination'), ('double', 'Double Elimination')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='bracket_side',
            field=models.CharField(choices=[('winners', 'Winners'), ('losers', 'Losers'), ('grand_final', 'Grand Final')], default='winners', max_length=15),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches_as_loser', to='brackets.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_next_match_slot',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Player 1'), (2, 'Player 2')], null=True),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('bracket', 'bracket_side', 'round_number', 'position'), name='unique_match_slot'),
        ),
    ]
