# Generated by Django 4.2.30 on 2026-07-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0002_alter_match_options_remove_match_unique_match_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group_label',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='format',
            field=models.CharField(choices=[('single', 'Single Elimination'), ('double', 'Double Elimination'), ('guarantee3', '3-Game Guarantee'), ('round_robin', 'Round Robin'), ('swiss', 'Swiss System'), ('group_playoff', 'Group Stage + Playoff')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='bracket_side',
            field=models.CharField(choices=[('winners', 'Winners'), ('losers', 'Losers'), ('grand_final', 'Grand Final'), ('guarantee', 'Guarantee')], default='winners', max_length=15),
        ),
    ]
