# Generated by Django 4.2.30 on 2026-07-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0003_match_group_label_alter_bracket_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='bracket_side',
            field=models.CharField(choices=[('winners', 'Winners'), ('losers', 'Losers'), ('grand_final', 'Grand Final'), ('guarantee', 'Guarantee'), ('group', 'Group')], default='winners', max_length=15),
        ),
    ]
