# Generated by Django 4.2.30 on 2026-08-19 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brackets', '0004_alter_match_bracket_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='forfeited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_forfeited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='is_forfeit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='organizer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
