# Generated by Django 4.2.30 on 2026-07-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_organizer_last_seen_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organizer',
            name='bank_account_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='organizer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='organizer',
            name='jazzcash_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organizer',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('jazzcash', 'JazzCash'), ('bank', 'Bank Account')], max_length=10),
        ),
    ]
