# Generated by Django 4.2.30 on 2026-08-02 13:38

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_organizer_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='cnic_document',
            field=models.FileField(blank=True, null=True, storage=core.storage.CloudinarySignedStorage(), upload_to='organizer/cnic/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='company_document',
            field=models.FileField(blank=True, null=True, storage=core.storage.CloudinarySignedStorage(), upload_to='organizer/company/%Y/%m/'),
        ),
    ]
