# Generated by Django 4.2.30 on 2026-08-02 14:00

import core.storage
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_alter_organizer_cnic_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='cnic_document',
            field=models.FileField(blank=True, null=True, storage=core.storage.CloudinarySignedStorage(), upload_to='organizer/cnic/%Y/%m/', validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='company_document',
            field=models.FileField(blank=True, null=True, storage=core.storage.CloudinarySignedStorage(), upload_to='organizer/company/%Y/%m/', validators=[core.validators.validate_document_file]),
        ),
    ]
