# Generated by Django 4.2.30 on 2026-08-02 17:30

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_alter_organizer_cnic_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, validators=[core.validators.validate_bank_account_number]),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='cnic_number',
            field=models.CharField(blank=True, max_length=20, validators=[core.validators.validate_cnic_number]),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='jazzcash_number',
            field=models.CharField(blank=True, max_length=30, validators=[core.validators.validate_pk_mobile_number]),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, validators=[core.validators.validate_phone_number]),
        ),
    ]
