# Generated by Django 4.2.30 on 2026-08-18 14:37

import core.storage
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_follow_follow_unique_follow_follow_no_self_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(default='user', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('cnic_number', models.CharField(blank=True, max_length=20)),
                ('cnic_document', models.FileField(blank=True, null=True, storage=core.storage.CloudinarySignedStorage(), upload_to='organizer/cnic/%Y/%m/', validators=[core.validators.validate_document_file])),
                ('company_registration_number', models.CharField(blank=True, max_length=100)),
                ('company_document', models.FileField(blank=True, null=True, storage=core.storage.CloudinarySignedStorage(), upload_to='organizer/company/%Y/%m/', validators=[core.validators.validate_document_file])),
                ('payout_method', models.CharField(blank=True, max_length=10)),
                ('jazzcash_number', models.CharField(blank=True, max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_title', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
