# Generated by Django 4.2.30 on 2026-08-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organizer_lifecycle_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreviewrequest',
            name='request_type',
            field=models.CharField(choices=[('tournament_cancellation', 'Tournament Cancellation'), ('registration_cancellation', 'Registration Cancellation')], max_length=40),
        ),
    ]
