# Generated by Django 4.2.30 on 2026-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registration_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreviewrequest',
            name='request_type',
            field=models.CharField(choices=[('tournament_cancellation', 'Tournament Cancellation'), ('registration_cancellation', 'Registration Cancellation'), ('bracket_reset', 'Bracket Reset')], max_length=40),
        ),
    ]
