# Generated by Django 4.2.30 on 2026-08-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_adminreviewrequest_requested_by_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adminreviewrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('content_type', 'object_id', 'request_type'), name='unique_pending_review_request_per_target_and_type'),
        ),
    ]
