# Generated by Django 4.2.30 on 2026-08-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_adminreviewrequest_unique_pending_review_request_per_target_and_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='otp_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
