# Generated by Django 4.2.30 on 2026-07-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_chat', '0002_chathistory_rulebook_remove_rule_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='game_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
